spring:
  application:
    name: investment-service

  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: false
      enabled: true
